name: Show Ubuntu VM Directory Contents

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  show-directory:
    runs-on: self-hosted
    name: Show contents of /home/pranav/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List contents of /home/pranav/
        run: ls -la /home/pranav/
