name: Connect to Ubuntu VM using Password

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: self-hosted  # Your Windows self-hosted runner
    steps:
      - name: Connect to Ubuntu VM using SSH with password
        env:
          SSH_USER: pranav
          SSH_PASSWORD: ${{ secrets.UBUNTU1 }}
          SSH_HOST: 192.168.1.100
        run: |
          # Create a PowerShell script to pass the password
          $password = ConvertTo-SecureString $env:SSH_PASSWORD -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential("$env:SSH_USER", $password)
          
          # Use the ssh command to connect to the Ubuntu VM
          ssh -o StrictHostKeyChecking=no $env:SSH_USER@$env:SSH_HOST "echo 'Logged in successfully!'"
          ssh -o StrictHostKeyChecking=no $env:SSH_USER@$env:SSH_HOST "ls -la /home/pranav/"
          ssh -o StrictHostKeyChecking=no $env:SSH_USER@$env:SSH_HOST "ifconfig"
          ssh -o StrictHostKeyChecking=no $env:SSH_USER@$env:SSH_HOST "whoami"
