name: Connect to Ubuntu VM using Password with Plink

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: self-hosted
    environment: ubuntu1  # Use the environment where your secret is stored
    steps:
      - name: Connect to Ubuntu VM using Plink and create a test file
        env:
          SSH_USER: pranav
          SSH_PASSWORD: ${{ secrets.UBUNTU1 }}
          SSH_HOST: 192.168.1.100
        shell: pwsh
        run: |
          # Download Plink if not already installed
          if (-Not (Get-Command plink -ErrorAction SilentlyContinue)) {
              Invoke-WebRequest -Uri "https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe" -OutFile "C:\Windows\System32\plink.exe"
          }
          # Use Plink to connect to the Ubuntu VM and create a test file
          echo y | plink -ssh $env:SSH_USER@$env:SSH_HOST -pw $env:SSH_PASSWORD "echo 'This is a test file created from GitHub Actions' > /home/pranav/git_target/test_file.txt"
          echo y | plink -ssh $env:SSH_USER@$env:SSH_HOST -pw $env:SSH_PASSWORD "ls -la /home/pranav/git_target"
