name: Run latest Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment and install dependencies
      - name: Setup Node.js and Install Dependencies
        run: |
          npm install

      # Step 3: Run the Node.js script to copy and execute the Python script on the remote VM
      - name: Run Node.js SSH script
        run: node scripts/deploy.js
