name: Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    steps:
      - run: |
          echo "Copying the Python script to Ubuntu VM..."
          pscp -pw "${{ secrets.UBUNTU1 }}" ./view_files.py "pranav@192.168.1.100:/home/pranav/git_target/"
          
          echo "Executing Python script on Ubuntu VM..."
          echo y | plink -ssh "pranav@192.168.1.100" -pw "${{ secrets.UBUNTU1 }}" "python3 /home/pranav/git_target/view_files.py"
