          
name: Connect to Ubuntu VM using Password with Plink
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  name: Windows Machine to Ubuntu VM
  ubuntu-ssh:
    runs-on: self-hosted

    environment: ubuntu1  # Use the environment where your secret is stored
    steps:
      - run: |
          echo "Executing on the Windows self-hosted runner."
          echo "Establishing SSH connection to Ubuntu VM..."
          echo y | plink -ssh "pranav@192.168.1.100" -pw "${{ secrets.UBUNTU1 }}" "echo 'This is a test file created from GitHub Actions' > /home/pranav/git_target/test_file.txt"
          echo "Test file created at /home/pranav/git_target/test_file.txt"
          echo y | plink -ssh "pranav@192.168.1.100" -pw "${{ secrets.UBUNTU1 }}" "ls -la /home/pranav/git_target"
          echo "Directory contents listed successfully."
