name: Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Variables and Execute Script
        shell: pwsh
        env:
          PASSWORD: ${{ secrets.ubuntu1 }}
        run: |
          # Set variables
          $USERNAME = "pranav"
          $REMOTE_HOST = "192.168.1.100"
          $TARGET_DIR = "/home/pranav/git_target"
          $LOCAL_SCRIPT = "./view_files.py"
          $REMOTE_SCRIPT = "$TARGET_DIR/view_files.py"
          
          # Display debug information (without printing the password)
          Write-Host "Connecting to $REMOTE_HOST as $USERNAME"
           
          # Step 2: Copy the Python script to the remote server
          pscp -pw $env:PASSWORD $LOCAL_SCRIPT "$USERNAME@$REMOTE_HOST:$TARGET_DIR/"
          
          # Step 3: Execute the Python script on the remote server
          echo y | plink -ssh "$USERNAME@$REMOTE_HOST" -pw $env:PASSWORD "python3 $REMOTE_SCRIPT"
