name: Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Copy the Python script to the Ubuntu VM
      - name: Copy Python Script to Ubuntu VM
        run: |
          echo "Copying the Python script to the Ubuntu VM..."
          # Copy the Python script using pscp
          pscp -pw "${{ secrets.UBUNTU1 }}" ./view_files.py "pranav@192.168.1.100:/home/pranav/git_target/"

      # Step 3: Establish SSH connection and run the Python script
      - name: Execute Python Script via SSH
        run: |
          echo "Connecting to Ubuntu VM and executing the Python script..."
          echo y | plink -ssh "pranav@192.168.1.100" -pw "${{ secrets.UBUNTU1 }}" "python3 /home/pranav/git_target/view_files.py"
