name: Connect to Ubuntu VM using Password

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: self-hosted  # Your Windows self-hosted runner
    environment: ubuntu1  # Use the environment where your secret is stored
    steps:
      - name: Check if environment secret is accessible
        env:
          SSH_PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          Write-Host "Checking if SSH_PASSWORD is set..."
          if ("$env:SSH_PASSWORD" -eq "") {
              Write-Host "❌ SSH_PASSWORD is empty!"
              exit 1
          } else {
              Write-Host "✅ SSH_PASSWORD is set."
              Write-Host "Password length: $($env:SSH_PASSWORD.Length)"
          }

      - name: Connect to Ubuntu VM using PowerShell and SSH
        env:
          SSH_USER: pranav
          SSH_PASSWORD: ${{ secrets.UBUNTU1 }}
          SSH_HOST: 192.168.1.100
        run: |
          # Use echo to pass the password and pipe it to the SSH command
          echo "$env:SSH_PASSWORD" | ssh -o StrictHostKeyChecking=no $env:SSH_USER@$env:SSH_HOST "ls -la /home/pranav/"
