name: Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      - name: Clone Repository and Execute Script via SSH
        run: |
          echo "Connecting to Ubuntu VM and cloning the repository..."
          echo y | plink -ssh "pranav@192.168.1.100" -pw "${{ secrets.UBUNTU1 }}" \
          "cd /home/pranav/git_target && \
          rm -rf intro && \
          git clone https://github.com/Pranav5Murali/intro.git && \
          cd intro && \
          python3 view_files.py"
