name: Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define variables
        run: |
          USERNAME="pranav"
          HOST="192.168.1.100"
          PASSWORD="${{ secrets.UBUNTU1 }}"
          TARGET_DIR="/home/pranav/git_target"
          LOCAL_SCRIPT="./view_files.py"
          REMOTE_SCRIPT="$TARGET_DIR/view_files.py"

      - name: Copy Python Script
        run: |
          pscp -pw "$PASSWORD" "$LOCAL_SCRIPT" "$USERNAME@$HOST:$TARGET_DIR/"

      - name: Execute Python Script via SSH
        run: |
          echo y | plink -ssh "$USERNAME@$HOST" -pw "$PASSWORD" "python3 $REMOTE_SCRIPT"
