name: Connect to Ubuntu VM using Password

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: self-hosted  # Your Windows self-hosted runner
    environment: Ubuntu  # Use the environment where your secret is stored
    steps:
      - name: Check if environment secret is accessible
        env:
          SSH_PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          Write-Host "Checking if SSH_PASSWORD is set..."
          if ("$env:SSH_PASSWORD" -eq "") {
            Write-Host "❌ SSH_PASSWORD is empty!"
            exit 1
          } else {
            Write-Host "✅ SSH_PASSWORD is set."
            Write-Host "Password length: $($env:SSH_PASSWORD.Length)"
          }

      - name: Connect to Ubuntu VM using SSH
        env:
          SSH_USER: pranav
          SSH_PASSWORD: ${{ secrets.UBUNTU1 }}
          SSH_HOST: 192.168.1.100
        run: |
          # Convert the password to a secure string
          $password = ConvertTo-SecureString $env:SSH_PASSWORD -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential("$env:SSH_USER", $password)
          ssh -o StrictHostKeyChecking=no $env:SSH_USER@$env:SSH_HOST "echo 'Logged in successfully!'"
