name: Deploy and Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy and Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy and Execute Script on Remote Server
        shell: pwsh
        env:
          USERNAME: "pranav"
          HOST: "192.168.1.100"
          PASSWORD: ${{ secrets.ubuntu1 }}
          TARGET_DIR: "/home/pranav/git_target"
          LOCAL_SCRIPT: "./view_files.py"
          REMOTE_SCRIPT: "/home/pranav/git_target/view_files.py"
        run: |
          # PowerShell Variables
          $username = $env:USERNAME
          $host = $env:HOST
          $password = $env:PASSWORD
          $targetDir = $env:TARGET_DIR
          $localScript = $env:LOCAL_SCRIPT
          $remoteScript = $env:REMOTE_SCRIPT
          
          # Step 1: Ensure the target directory exists on the remote server
          Write-Host "Creating target directory on $host..."
          plink -ssh "${username}@${host}" -pw $password "mkdir -p $targetDir"

          # Step 2: Copy the Python script to the remote server
          Write-Host "Copying Python script to remote server..."
          pscp -pw $password $localScript "${username}@${host}:`${targetDir}/"

          # Step 3: Execute the Python script on the remote server
          Write-Host "Executing Python script on remote server..."
          $executionResult = plink -ssh "${username}@${host}" -pw $password "python3 $remoteScript"

          # Check for errors in script execution
          if ($executionResult -like "*Error*") {
              Write-Error "Error occurred during script execution on the remote server"
              exit 1
          } else {
              Write-Host "Python script executed successfully."
