name: Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    name: Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3


      # Step 3: Copy the Python script to the Ubuntu VM
      - name: Copy Python Script to Ubuntu VM
        run: |
          echo "Copying the Python script to Ubuntu VM..."
          pscp -pw "${{ secrets.UBUNTU1 }}" ./view_files.py "pranav@192.168.1.100:/home/pranav/git_target/"
      
      # Step 4: Execute the Python script on the Ubuntu VM
      - name: Execute Python Script via SSH
        run: |
          echo "Executing Python script on Ubuntu VM..."
          echo y | plink -ssh "pranav@192.168.1.100" -pw "${{ secrets.UBUNTU1 }}" "python3 /home/pranav/git_target/view_files.py"
