      - name: Execute Script on Remote Server (Python)
        shell: python
        env:
          USERNAME: "pranav"
          HOST: "192.168.1.100"
          PASSWORD: ${{ secrets.ubuntu1 }}
          REMOTE_SCRIPT: "/home/pranav/git_target/view_files.py"
        run: |
          import os
          import subprocess

          username = os.getenv("USERNAME")
          host = os.getenv("HOST")
          password = os.getenv("PASSWORD")
          remote_script = os.getenv("REMOTE_SCRIPT")

          command = f'sshpass -p "{password}" ssh -o StrictHostKeyChecking=no {username}@{host} "python3 {remote_script}"'
          result = subprocess.run(command, shell=True, capture_output=True, text=True)
          
          if result.returncode != 0:
              print(f"Error: {result.stderr}")
              exit(1)
          else:
              print(f"Success: {result.stdout}")
