name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      # Run the Bash script using both secrets and variables
      - name: Copy and Execute Bash Script from Beta Branch
        env:
          DEST_USER: ${{ vars.DEST_USER }}    # Access variables
          DEST_IP: ${{ vars.DEST_IP }}        # Access variables
          VM_PWD: ${{ secrets.VM_PWD }}       # Access secret
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "$DEST_USER" "$DEST_IP" "$VM_PWD" "test.py"
