name: Deploy and Run Python Script on Remote Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Windows self-hosted runner

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up environment variables from GitHub secrets
      - name: Set up Environment Variables
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.ubuntu1 }}
        run: |
          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
          echo "HOST=${HOST}" >> $GITHUB_ENV
          echo "PASSWORD=${PASSWORD}" >> $GITHUB_ENV
          echo "TARGET_DIR=/home/pranav/git_target" >> $GITHUB_ENV
          echo "LOCAL_SCRIPT=./view_files.py" >> $GITHUB_ENV
          echo "REMOTE_SCRIPT=/home/pranav/git_target/view_files.py" >> $GITHUB_ENV

      # Step 3: Execute the Python deployment script
      - name: Run Deployment Script
        run: python deploy_script.py
