name: Deploy and Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Environment Variables from Secrets
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
          echo "HOST=${HOST}" >> $GITHUB_ENV
          echo "PASSWORD=${PASSWORD}" >> $GITHUB_ENV

      - name: Execute Python Script
        run: python3 deploy_script.py
