name: Deploy and Execute Script on Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy-and-execute:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set environment variables using secrets
      - name: Set environment variables
        env:
          USERNAME: pranav
          HOST: ${{ secrets.UBUNTU_HOST }}
          PASSWORD: ${{ secrets.UBUNTU1 }}
          TARGET_DIR: /home/pranav/scripts
          LOCAL_SCRIPT: intro/view_files.py
          REMOTE_SCRIPT: /home/pranav/scripts/view_files.py
        run: echo "Environment variables set."

      # Step 3: Copy the Python script to the remote Ubuntu server using `pscp`
      - name: Copy script to remote server using pscp
        shell: pwsh
        run: |
          & "C:\Program Files\PuTTY\pscp.exe" -pw "$env:PASSWORD" -batch -scp "$env:LOCAL_SCRIPT" "$env:USERNAME@$env:HOST:$env:TARGET_DIR/"

      # Step 4: Execute the Python script on the remote Ubuntu server using `plink`
      - name: Execute script on remote server using plink
        shell: pwsh
        run: |
          & "C:\Program Files\PuTTY\plink.exe" -pw "$env:PASSWORD" -batch "$env:USERNAME@$env:HOST" "/usr/bin/python3 $env:REMOTE_SCRIPT"
