name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch:
    branches:
      - Beta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debugging step: Check if environment variables are set correctly
      - name: Debug environment variables
        env:
          DEST_USER: ${{ secrets.DEST_USER }}
          DEST_IP: ${{ secrets.DEST_IP }}
          VM_PWD: ${{ secrets.VM_PWD }}
        run: |
          echo "DEST_USER: $DEST_USER"
          echo "DEST_IP: $DEST_IP"
          echo "VM_PWD: *** (hidden for security)"

      # Copy and execute the Bash script
      - name: Copy Python Script to Remote Server and Execute
        env:
          DEST_USER: ${{ secrets.DEST_USER }}
          DEST_IP: ${{ secrets.DEST_IP }}
          VM_PWD: ${{ secrets.VM_PWD }}
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "$DEST_USER" "$DEST_IP" "$VM_PWD" "test.py"
