name: Deploy and Execute Script using Plink

on:
  push:
    branches:
      - main

jobs:
  deploy-and-execute:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set environment variables using secrets
      - name: Set environment variables
        env:
          USERNAME: pranav
          HOST: ${{ secrets.ubuntu_host }}
          PASSWORD: ${{ secrets.ubuntu1 }}
          TARGET_DIR: /home/pranav/scripts
          LOCAL_SCRIPT: intro/view_files.py
          REMOTE_SCRIPT: /home/pranav/scripts/view_files.py
        run: echo "Environment variables set."

      # Step 3: Copy the script to the remote server using `pscp`
      - name: Copy script to remote server using pscp
        shell: pwsh
        run: |
          pscp -pw "$PASSWORD" -batch -scp $LOCAL_SCRIPT $USERNAME@$HOST:$TARGET_DIR/

      # Step 4: Execute the script on the remote server using `plink`
      - name: Execute script on remote server using plink
        shell: pwsh
        run: |
          plink -pw "$PASSWORD" -batch $USERNAME@$HOST "/usr/bin/python3 $REMOTE_SCRIPT"
