name: Deploy and Execute Script using Plink

on:
  push:
    branches:
      - main

jobs:
  deploy-and-execute:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set environment variables from secrets
      - name: Set environment variables
        env:
          USERNAME: pranav
          HOST: 192.168.1.100
          PASSWORD: ${{ secrets.ubuntu1 }}
          TARGET_DIR: /home/pranav/scripts
          LOCAL_SCRIPT: intro/view_files.py
          REMOTE_SCRIPT: /home/pranav/scripts/view_files.py
        run: echo "Environment variables set."

      # Step 3: Copy the Python script to the remote Ubuntu server using pscp
      - name: Copy script to remote server using pscp
        shell: pwsh
        run: |
          pscp -pw "$PASSWORD" -scp -batch $LOCAL_SCRIPT $USERNAME@$HOST:$TARGET_DIR/

      # Step 4: Execute the Python script on the remote server using plink
      - name: Execute script on remote server using plink
        shell: pwsh
        run: |
          plink -pw "$PASSWORD" -batch $USERNAME@$HOST "/usr/bin/python3 $REMOTE_SCRIPT"

      # Step 5: Run the script locally using the system-installed Python
      - name: Run Python script locally
        shell: pwsh
        run: |
          C:\Users\Pranav\AppData\Local\Programs\Python\Python38\python.exe intro/deploy_script.py
