name: Deploy and Execute Script using Plink

on:
  push:
    branches:
      - main

jobs:
  deploy-and-execute:
    runs-on: self-hosted
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment on the runner (Ubuntu VM)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Set environment variables from secrets
      - name: Set environment variables
        env:
          USERNAME: pranav
          HOST: 192.168.1.100
          PASSWORD: ${{ secrets.ubuntu1 }}
          TARGET_DIR: /home/pranav/scripts
          LOCAL_SCRIPT: intro/view_files.py
          REMOTE_SCRIPT: /home/pranav/scripts/view_files.py
        run: echo "Environment variables set."

      # Step 4: Copy the Python script to the remote Ubuntu server using pscp
      - name: Copy script to remote server using pscp
        run: |
          pscp -pw "$PASSWORD" -scp -batch $LOCAL_SCRIPT $USERNAME@$HOST:$TARGET_DIR/

      # Step 5: Execute the Python script on the remote server using plink
      - name: Execute script on remote server using plink
        run: |
          plink -pw "$PASSWORD" -batch $USERNAME@$HOST "/usr/bin/python3 $REMOTE_SCRIPT"
