name: Deploy and Execute Script on Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy-and-execute:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set environment variables
      - name: Set environment variables
        shell: pwsh
        run: |
          # Manually set the values
          $env:USERNAME = "pranav"
          $env:HOST = "192.168.1.100" # Replace this with your actual Ubuntu server IP address
          $env:PASSWORD = "${{ secrets.UBUNTU1 }}"
          $env:TARGET_DIR = "/home/pranav/git_target"
          $env:LOCAL_SCRIPT = "intro/view_files.py"
          $env:REMOTE_SCRIPT = "/home/pranav/git_target/view_files.py"

          # Debugging output
          echo "USERNAME: $env:USERNAME"
          echo "HOST: $env:HOST"
          echo "TARGET_DIR: $env:TARGET_DIR"
          echo "LOCAL_SCRIPT: $env:LOCAL_SCRIPT"
          echo "REMOTE_SCRIPT: $env:REMOTE_SCRIPT"

          if (-Not $env:HOST) { Write-Error "HOST is not set" }
          if (-Not $env:PASSWORD) { Write-Error "PASSWORD is not set" }

      # Step 3: Copy the Python script to the remote server using `pscp`
      - name: Copy script to remote server using pscp
        shell: pwsh
        run: |
          & "C:\Program Files\PuTTY\pscp.exe" -pw "$env:PASSWORD" -batch -scp "$env:LOCAL_SCRIPT" "$env:USERNAME@$env:HOST:$env:TARGET_DIR/"

      # Step 4: Execute the Python script on the
