name: Check Ubuntu Host Connectivity

on:
  push:
    branches:
      - main

jobs:
  check-connectivity:
    runs-on: self-hosted

    steps:
      # Step 1: Set environment variables using GitHub secrets
      - name: Set environment variables
        env:
          USERNAME: pranav
          HOST: 192.168.1.100 # Replace this with your actual Ubuntu server IP address
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          echo "USERNAME: $env:USERNAME"
          echo "HOST: $env:HOST"
          
          # Check if the PASSWORD is set
          if (-Not $env:PASSWORD) {
            Write-Error "PASSWORD is not set correctly!"
            exit 1
          } else {
            echo "PASSWORD is set correctly."
          }

      # Step 2: Check connectivity using plink
      - name: Check connectivity to Ubuntu server
        shell: pwsh
        run: |
          & "C:\Program Files\PuTTY\plink.exe" -pw "$env:PASSWORD" -batch "$env:USERNAME@$env:HOST" "echo Connected successfully"
