name: Connect to Ubuntu VM using Plink and PSCP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
      # Set up environment variables and check them using PowerShell Core
      - name: Check environment variables
        run: |
          echo "Checking environment variables..."
          echo "Python Version: $($env:PYTHON_VERSION)"
          echo "Node Version: $($env:NODE_VERSION)"
          echo "PowerShell Path: $($env:POWERSHELL_PATH)"
          echo "Plink Path: $($env:PUTTY_PATH\\plink.exe)"
          
          # Check if the PASSWORD is set correctly
          if (-not $env:PASSWORD) {
            Write-Error "ERROR: PASSWORD is not set correctly!"
            exit 1
          } else {
            echo "PASSWORD is set correctly."
          }
        shell: pwsh

      # Test SSH connection using Plink
      - name: Test SSH connection using Plink
        env:
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          & "$env:PUTTY_PATH\\plink.exe" -ssh -pw $env:PASSWORD -noagent -batch pranav@192.168.1.100 "hostname && whoami"
        shell: pwsh

      # Transfer a file to the Ubuntu VM using PSCP
      - name: Transfer file using PSCP
        env:
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          & "$env:PUTTY_PATH\\pscp.exe" -pw $env:PASSWORD C:\\path\\to\\your\\file.txt pranav@192.168.1.100:/home/pranav/
        shell: pwsh
