name: Check Ubuntu Host Connectivity

on:
  push:
    branches:
      - main

jobs:
  check-connectivity:
    runs-on: self-hosted

    steps:
      # Step 1: Set environment variables using GitHub secrets
      - name: Set environment variables
        env:
          USERNAME: pranav
          HOST: 192.168.1.100 # Replace this with your actual Ubuntu server IP address
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          echo "Checking environment variables..."
          echo "USERNAME: $env:USERNAME"
          echo "HOST: $env:HOST"

          # Check if the PASSWORD is set correctly
          if (-Not $env:PASSWORD) {
            Write-Error "ERROR: PASSWORD is not set correctly!"
            exit 1
          } else {
            echo "PASSWORD is set correctly."
          }

      # Step 2: Test SSH connectivity using plink
      - name: Test SSH connectivity with plink
        shell: pwsh
        run: |
          echo "Testing connectivity to $env:USERNAME@$env:HOST..."
          try {
            & "C:\Program Files\PuTTY\plink.exe" -v -pw "$env:PASSWORD" -batch "$env:USERNAME@$env:HOST" "echo Connected successfully"
          } catch {
            Write-Error "ERROR: Failed to connect to $env:HOST"
            exit 1
          }
