name: Debug Environment Variables

on:
  workflow_dispatch:

jobs:
  check-env:
    runs-on: self-hosted
    steps:
      - name: Print Environment Variables
        shell: pwsh
        run: |
          Write-Host "Python Version: $env:PYTHON_VERSION"
          Write-Host "Node Version: $env:NODE_VERSION"
          Write-Host "PowerShell Path: $env:POWERSHELL_PATH"
          Write-Host "Plink Path: $env:PUTTY_PATH\\plink.exe"
          
          if (-not $env:PASSWORD) {
            Write-Error "ERROR: PASSWORD is not set!"
          } else {
            Write-Host "PASSWORD is set correctly."
