name: Connect to Ubuntu VM using Plink and PSCP

on:
  workflow_dispatch:
    # Allows manually triggering the workflow

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
      # Set up environment variables from your runner's .env file
      - name: Set up environment variables
        run: |
          $env:PLINK_PATH = "C:\\Program Files\\PuTTY\\plink.exe"
          $env:PSCP_PATH = "C:\\Program Files\\PuTTY\\pscp.exe"
          $env:PYTHON_PATH = "C:\\Users\\Pranav\\AppData\\Local\\Programs\\Python\\Python38\\python.exe"
          $env:NODE_PATH = "C:\\Program Files\\nodejs\\node.exe"
        shell: powershell

      - name: Check Python and Node versions
        run: |
          &"$env:PYTHON_PATH" --version
          &"$env:NODE_PATH" -v
        shell: powershell

      # Step to test connection to Ubuntu VM using Plink
      - name: Test SSH connection using Plink
        env:
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          &"$env:PLINK_PATH" -ssh -pw $env:PASSWORD -noagent -batch pranav@192.168.1.100 "hostname && whoami"
        shell: powershell

