name: Test GitHub Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: self-hosted

    steps:
      # Step 1: Check if the secret is retrieved correctly
      - name: Check Secret UBUNTU1
        env:
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          echo "Checking if PASSWORD is set..."
          
          # Check if the PASSWORD is set correctly
          if (-Not $env:PASSWORD) {
            Write-Error "ERROR: PASSWORD is not set correctly!"
            exit 1
          } else {
            echo "PASSWORD is set and its length is: $(($env:PASSWORD).Length) characters"
          }
