name: Debug Environment Variables

on:
  workflow_dispatch:

jobs:
  check-env:
    runs-on: self-hosted
    steps:
      - name: Check if PowerShell Core exists
        run: |
          dir "C:\Program Files\PowerShell\7\pwsh.exe"
      
      - name: Print Environment Variables using cmd
        run: |
          cmd.exe /c ""C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'Python Version: $env:PYTHON_VERSION'""
          cmd.exe /c ""C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'Node Version: $env:NODE_VERSION'""
          cmd.exe /c ""C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'PowerShell Path: $env:POWERSHELL_PATH'""
          cmd.exe /c ""C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'Plink Path: $env:PUTTY_PATH\\plink.exe'""
