name: Debug Environment Variables and SSH Connection

on:
  workflow_dispatch:
    # Manually trigger the workflow

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
      # Step 1: Check if environment variables are being picked up
      - name: Print Environment Variables
        shell: pwsh
        run: |
          Write-Host "Checking environment variables..."
          Write-Host "Python Version: $env:PYTHON_VERSION"
          Write-Host "Node Version: $env:NODE_VERSION"
          Write-Host "PowerShell Path: $env:POWERSHELL_PATH"
          Write-Host "Plink Path: $env:PUTTY_PATH\\plink.exe"
          Write-Host "SSH Password: $env:PASSWORD"

      # Step 2: Test if PASSWORD is correctly set
      - name: Check if PASSWORD is set
        shell: pwsh
        run: |
          if (-not $env:PASSWORD) {
            Write-Error "ERROR: PASSWORD is not set correctly!"
            exit 1
          } else {
            Write-Host "PASSWORD is set correctly."
          }

      # Step 3: Test SSH connection to Ubuntu VM using Plink
      - name: Test SSH connection using Plink
        shell: pwsh
        env:
          PASSWORD: ${{ secrets.UBUNTU1 }}
        run: |
          & "$env:PUTTY_PATH\\plink.exe" -ssh -pw $env:PASSWORD -noagent -batch pranav@192.168.1.100 "hostname && whoami"
