name: Debug Environment Variables

on:
  workflow_dispatch:

jobs:
  check-env:
    runs-on: self-hosted
    steps:
      - name: Check if PowerShell Core exists
        run: |
          dir "C:\Program Files\PowerShell\7\pwsh.exe"
      
      - name: Print Environment Variables using PowerShell Core
        run: |
          "C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'Python Path: $env:PYTHON_HOME'"
          "C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'Node Path: $env:NODE_HOME'"
          "C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'PowerShell Path: $env:POWERSHELL_HOME'"
          "C:\Program Files\PowerShell\7\pwsh.exe" -Command "Write-Host 'Putty Path: $env:PUTTY_HOME\\plink.exe'"
