name: Test PuTTY

on: [push]

jobs:
  test-putty:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - name: Print PATH
        run: echo $env:PATH
      - name: Check PuTTY
        run: &"C:\Program Files\PuTTY\putty.exe"
