name: Test PowerShell Availability

on:
  workflow_dispatch:

jobs:
  test-powershell:
    runs-on: self-hosted
    steps:
      - name: Check if PowerShell Core (pwsh) is available
        run: |
          echo "Testing PowerShell Core availability..."
          pwsh -Command "Write-Host 'PowerShell Core is available'"
      
      - name: Display PowerShell Version
        run: |
          pwsh -Command "$PSVersionTable.PSVersion"
