name: Test PuTTY

on: [push]

jobs:
  test-putty:
    runs-on: self-hosted
    steps:
      - name: Print PATH
        run: echo $env:PATH
        shell: powershell
      - name: Check PuTTY
        run: putty
        shell: powershell
