name: Deploy and Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy and Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 1: Copy the Python script to the remote server using `pscp`
      - name: Copy Script to Remote Server
        shell: pwsh
        run: |
          echo "Copying Python script to remote server..."
          pscp -pw "${{ secrets.ubuntu1 }}" -scp ./view_files.py "pranav@192.168.1.100:/home/pranav/git_target/"

      # Step 2: Execute the Python script on the remote server using `plink`
      - name: Execute Python Script on Remote Server
        shell: pwsh
        run: |
          echo "Executing Python script on remote server..."
          plink -ssh -pw "${{ secrets.ubuntu1 }}" "pranav@192.168.1.100" "/usr/bin/python3 /home/pranav/git_target/view_files.py"
