name: Test plink

on:
  workflow_dispatch:

jobs:
  connect-ubuntu:
    runs-on: self-hosted
    name: Connect to Ubuntu VM using plink

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Connect to Ubuntu VM via plink
      shell: pwsh
      run: |
        echo "Connecting to Ubuntu VM..."
        & "C:\Program Files\PuTTY\plink.exe" -ssh pranav@192.168.1.100 -pw "${{ secrets.UBUNTU1 }}" -m commands.txt
