name: Test PuTTY

on: 
  push:

jobs:
  test-putty:
    runs-on: self-hosted
    steps:
      - name: Print PATH (Windows)
        run: |
          echo %PATH%
        shell: cmd

      - name: Check PuTTY
        run: "C:\\Program Files\\PuTTY\\putty.exe"
        shell: cmd
