name: Test putty

on:
  workflow_dispatch:

jobs:
  connect-ubuntu:
    runs-on: self-hosted
    name: Connect to Ubuntu VM from Windows Runner

    steps:
    # Checkout the code repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Connect to Ubuntu VM via SSH using the stored secret
    - name: Connect to Ubuntu VM via SSH
      run: |
        echo "Connecting to Ubuntu VM..."
        putty -ssh pranav@192.168.1.100 -pw ${{ secrets.UBUNTU1 }} -m commands.txt
      env:
        UBUNTU_PASSWORD: ${{ secrets.UBUNTU1 }}
