name: Test plink

on:
  workflow_dispatch:

jobs:
  connect-ubuntu:
    runs-on: self-hosted
    name: Connect to Ubuntu VM using plink

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to debug the secret using classic Windows PowerShell
    - name: Debug secret in powershell
      shell: powershell
      run: |
        Write-Host "Checking if UBUNTU1 or ubuntu1 secret is set..."
        
        # Check for both uppercase and lowercase versions of the secret
        if (($Env:UBUNTU1 -eq $null -or $Env:UBUNTU1 -eq "") -and ($Env:ubuntu1 -eq $null -or $Env:ubuntu1 -eq "")) {
          Write-Host "Neither UBUNTU1 nor ubuntu1 secrets are set or they are empty"
          exit 1
        } else {
          if ($Env:UBUNTU1 -ne $null -and $Env:UBUNTU1 -ne "") {
            Write-Host "Using UBUNTU1"
            $password = $Env:UBUNTU1
          } else {
            Write-Host "Using ubuntu1"
            $password = $Env:ubuntu1
          }
          Write-Host "Length of password: $($password.Length)"
        }

    # Step to connect to the Ubuntu VM using plink
    - name: Connect to Ubuntu VM via plink
      shell: powershell
      run: |
        Write-Host "Connecting to Ubuntu VM..."
        
        # Use the password variable set in the previous step
        if ($password -eq $null -or $password -eq "") {
          Write-Host "Password is missing!"
          exit 1
        }
        Write-Host "Using password (first 4 chars): $($password.Substring(0, 4))..."
        & "C:\Program Files\PuTTY\plink.exe" -ssh pranav@192.168.1.100 -pw $password -m commands.txt
