name: Test plink

on:
  workflow_dispatch:

jobs:
  connect-ubuntu:
    runs-on: self-hosted
    name: Connect to Ubuntu VM using plink

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to debug the secret using classic Windows PowerShell
    - name: Debug secret in powershell
      shell: powershell
      env:
        UBUNTU1: ${{ secrets.UBUNTU1 }}
      run: |
        Write-Host "Checking if UBUNTU1 secret is set..."
        
        # Check if the UBUNTU1 secret is set and not empty
        if ($Env:UBUNTU1 -eq $null -or $Env:UBUNTU1 -eq "") {
          Write-Host "Secret UBUNTU1 is not set or is empty"
          exit 1
        } else {
          Write-Host "Secret UBUNTU1 is set"
          Write-Host "Length of password: $($Env:UBUNTU1.Length)"
        }

    # Step to connect to the Ubuntu VM using plink
    - name: Connect to Ubuntu VM via plink
      shell: powershell
      env:
        password: ${{ secrets.UBUNTU1 }}
      run: |
        Write-Host "Connecting to Ubuntu VM..."
        
        # Check if the password is available
        if ($Env:password -eq $null -or $Env:password -eq "") {
          Write-Host "Password is missing!"
          exit 1
        }
        Write-Host "Using password (first 4 chars): $($Env:password.Substring(0, 4))..."
        & "C:\Program Files\PuTTY\plink.exe" -ssh pranav@192.168.1.100 -pw $Env:password -m commands.txt
