name: Test PuTTY

on: 
  push:

jobs:
  test-putty:
    runs-on: self-hosted
    steps:
      - name: Print PATH (using cmd.exe)
        run: |
          cmd.exe /c "echo %PATH%"
      
      - name: Check PuTTY (using cmd.exe)
        run: |
          cmd.exe /c "C:\\Program Files\\PuTTY\\putty.exe"
