name: Test plink

on:
  workflow_dispatch:

jobs:
  connect-ubuntu:
    runs-on: self-hosted
    name: Connect to Ubuntu VM using plink

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug secret
      shell: bash
      run: |
        if [ -z "${{ secrets.UBUNTU1 }}" ]; then
          echo "Secret UBUNTU1 is not set or is empty"
        else
          echo "Secret UBUNTU1 length: ${#UBUNTU1}"
        fi

    - name: Connect to Ubuntu VM via plink using cmd
      shell: cmd
      run: |
        echo Connecting to Ubuntu VM...
        "C:\Program Files\PuTTY\plink.exe" -ssh pranav@192.168.1.100 -pw "${{ secrets.UBUNTU1 }}" -m commands.txt
