name: Run Python Script Advanced

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print current directory
      shell: cmd
      run: |
        echo "Current directory:"
        cd
        echo "Contents of current directory:"
        dir

    - name: Run Python script using cmd
      shell: cmd
      env:
        UBUNTU1: ${{ secrets.UBUNTU1 }}
      run: |
        echo "Running Python script using cmd..."
        cd "${{ github.workspace }}"
        dir
        "C:\Users\Pranav\AppData\Local\Programs\Python\Python38\python.exe" execute_remote.py
