name: Run Python Script Advanced

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Python script using Git Bash
      shell: cmd
      env:
        UBUNTU1: ${{ secrets.UBUNTU1 }}
      run: |
        echo "Running Python script using Git Bash..."
        cd "${{ github.workspace }}"
        "C:\Program Files\Git\bin\bash.exe" -c '"C:/Users/Pranav/AppData/Local/Programs/Python/Python38/python.exe" execute_remote.py'

