name: Run Python Script on Ubuntu VM

on:
  workflow_dispatch:

jobs:
  execute-python:
    runs-on: self-hosted
    environment: ubuntu1
    name: Execute Python Script on Ubuntu VM using plink

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Step to connect to the Ubuntu VM using plink and execute the Python script
    - name: Run Python Script on Ubuntu VM
      shell: powershell
      env:
        password: ${{ secrets.UBUNTU1 }}
      run: |
        Write-Host "Connecting to Ubuntu VM..."
        
        # Execute the Python script directly using plink
        & "C:\Program Files\PuTTY\plink.exe" `
          -ssh pranav@192.168.1.100 `
          -pw $Env:password `
          "cd /home/pranav/Documents && python3 view_files.py"
