name: Run Python Script Advanced

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Python script
      shell: C:/Program Files/Git/bin/bash.exe
      env:
        UBUNTU1: ${{ secrets.UBUNTU1 }}
      run: |
        echo "Running Python script using Git Bash..."
        /c/Path/To/Python/python.exe execute_remote.py
