name: Run Python Script Advanced

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Python script
      shell: powershell
      env:
        UBUNTU1: ${{ secrets.UBUNTU1 }}
      run: python execute_remote.py
