name: Deploy and Run Python Script on Ubuntu VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy and Execute Python Script on Ubuntu VM
    runs-on: self-hosted
    environment: ubuntu1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          echo "USERNAME=pranav" >> $GITHUB_ENV
          echo "HOST=192.168.1.100" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.ubuntu1 }}" >> $GITHUB_ENV
          echo "TARGET_DIR=/home/pranav/git_target" >> $GITHUB_ENV
          echo "LOCAL_SCRIPT=./view_files.py" >> $GITHUB_ENV
          echo "REMOTE_SCRIPT=/home/pranav/git_target/view_files.py" >> $GITHUB_ENV

      - name: Execute Python Script
        run: python3 deploy_script.py
