name: Test Connection to Remote Server

on:
  workflow_dispatch:

jobs:
  connect-to-server:
    runs-on: self-hosted
    environment: ubuntu1  # Specify the environment here
    name: Test Access to Secret and Connection
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Secret Password
        run: |
          chmod +x fetch_password.sh
          ./fetch_password.sh
        env:
          UBUNTU1: ${{ secrets.UBUNTU1 }}
