name: Test Secret Access and SSH Connection

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    name: Test Access to Secret and Connection
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Secret Fetching
        run: |
          echo "Attempting to fetch the secret UBUNTU1"
          if [ -z "${{ secrets.UBUNTU1 }}" ]; then
            echo "Error: Secret UBUNTU1 is empty or not accessible"
            exit 1
          else
            echo "Secret UBUNTU1 fetched successfully"
          fi

      - name: Print Secret Length (Masked)
        run: |
          echo "::add-mask::${{ secrets.UBUNTU1 }}"
          echo "Secret length: ${#secrets.UBUNTU1}"

      - name: Test SSH Connection Using Bash Script
        run: |
          chmod +x connect.sh
          ./connect.sh "${{ secrets.UBUNTU1 }}" "192.168.1.105" "karthik"
        shell: bash

