name: Test Connection to Remote Server

on:
  workflow_dispatch:

jobs:
  connect-to-server:
    runs-on: self-hosted
    name: Test Connection to Ubuntu Mate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step to fetch and validate the secret
      - name: Fetch Secret Password
        run: |
          echo "Fetching the password from secret..."
          echo "PASSWORD=${{ secrets.UBUNTU1 }}" >> $GITHUB_ENV

      - name: Validate Secret Fetching
        run: |
          if [ -z "${{ env.PASSWORD }}" ]; then
            echo "Error: Secret password is empty"
            exit 1
          else
            echo "Secret password fetched successfully"
          fi

      # Run the shell script to connect to the remote machine
      - name: Run Connection Script
        run: |
          chmod +x connect.sh
          ./connect.sh "${{ env.PASSWORD }}" "192.168.1.105" "karthik"
        shell: bash
