name: Test Connection to Ubuntu Mate

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: self-hosted
    name: Connect to Destination VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch the secret directly from GitHub secrets
      - name: Fetch Secret Password
        id: fetch_secret
        run: |
          echo "Secret fetched successfully"

      # Debugging step to verify if the secret is being fetched correctly
      - name: Verify Secret Access
        run: |
          echo "VM_PASSWORD=${{ secrets.UBUNTU1 }}"
          if [ -z "${{ secrets.UBUNTU1 }}" ]; then
            echo "Error: Secret UBUNTU1 is empty"
            exit 1
          fi

      # Use the fetched secret to connect via SSH
      - name: Test SSH connection using bash script
        run: |
          chmod +x connect.sh
          ./connect.sh "${{ secrets.UBUNTU1 }}" "192.168.1.105" "karthik"
        shell: bash
