name: Test Connection to Ubuntu Mate

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: self-hosted
    name: Connect to Destination VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch secrets
        env:
          VM_PASSWORD: ${{ secrets.UBUNTU1 }}
        run: echo "Password fetched for connection"

      - name: Test SSH connection using bash script
        run: |
          chmod +x connect.sh
          ./connect.sh "$VM_PASSWORD" "192.168.1.105" "karthik"

