name: Test Connection to Ubuntu Mate

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: self-hosted
    name: Connect to Destination VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and export secrets
        run: echo "VM_PASSWORD=${{ secrets.Ubuntu1 }}" >> $GITHUB_ENV

      - name: Test SSH connection using bash script
        run: |
          chmod +x connect.sh
          ./connect.sh "${{ env.VM_PASSWORD }}" "192.168.1.105" "karthik"
        shell: bash

