name: Test Connection to Ubuntu Mate

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: self-hosted
    name: Connect to Destination VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debugging step to ensure secret is fetched and escaped properly
      - name: Fetch and export the secret
        id: fetch_secret
        run: |
          echo "Secret fetched"
          echo "VM_PASSWORD=${{ secrets.UBUNTU1 }}" >> $GITHUB_ENV

      # Additional debug to check the secret content (temporarily, remove after confirming)
      - name: Verify Secret Fetch
        run: |
          echo "::add-mask::${{ secrets.UBUNTU1 }}"  # Masks the secret in logs
          echo "Secret length: ${#secrets.UBUNTU1}"
          if [ -z "${{ secrets.UBUNTU1 }}" ]; then
            echo "Error: Secret UBUNTU1 is empty"
            exit 1
          fi

      # Run the bash script with the escaped password
      - name: Test SSH connection using bash script
        run: |
          chmod +x connect.sh
          ./connect.sh "${{ secrets.UBUNTU1 }}" "192.168.1.105" "karthik"
        shell: bash
