name: Test Connection to Ubuntu Mate

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: self-hosted
    name: Connect to Destination VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to print and fetch the secret
      - name: Fetch Secret Password
        id: fetch_secret
        run: |
          echo "Fetching secret..."
          echo "VM_PASSWORD=${{ secrets.UBUNTU1 }}" >> $GITHUB_ENV
          echo "Secret fetched successfully"

      # Debugging step to verify if the secret is set
      - name: Verify Environment Variables
        run: |
          echo "VM_PASSWORD: ${{ env.VM_PASSWORD }}"
          if [ -z "${{ env.VM_PASSWORD }}" ]; then
            echo "Error: VM_PASSWORD is empty"
            exit 1
          fi

      - name: Test SSH connection using bash script
        run: |
          chmod +x connect.sh
          ./connect.sh "${{ env.VM_PASSWORD }}" "192.168.1.105" "karthik"
        shell: bash
