name: View Files on Remote VM

on:
  workflow_run:
    workflows: ["Deploy and Run Python Script"]
    types:
      - completed

jobs:
  view-files:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Environment Variables from Secrets
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
          echo "HOST=${HOST}" >> $GITHUB_ENV
          echo "PASSWORD=${PASSWORD}" >> $GITHUB_ENV
          echo "REMOTE_SCRIPT=/home/pranav/git_target/view_files.py" >> $GITHUB_ENV

      - name: Install sshpass
        run: sudo apt update && sudo apt install -y sshpass

      - name: Execute View Files Script
        run: |
          sshpass -p "${PASSWORD}" ssh -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "/usr/bin/python3 ${REMOTE_SCRIPT}"
