name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, X64, Linux]

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      # Run the Bash script with hardcoded credentials
      - name: Copy and Execute Bash Script
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "Test@123" "test.py"
