name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    # Use your self-hosted runner
    runs-on: [self-hosted, X64, Linux]

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      # Run the Bash script to copy and execute the Python script on the remote server
      - name: Copy Python Script to Remote Server
        env:
          DEST_USER: ${{ vars.DEST_USER }}    # Access variables
          DEST_IP: ${{ vars.DEST_IP }}        # Access variables
          VM_PWD: ${{ secrets.VM_PWD }}       # Access secrets
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "$DEST_USER" "$DEST_IP" "$VM_PWD" "test.py"
