name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    # Use your self-hosted runner
    runs-on: [self-hosted, X64, Linux]

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      # Run the Bash script using the updated secret for VM_PWD
      - name: Copy and Execute Bash Script
        env:
          DEST_USER: "karthik"        # Hardcoded username
          DEST_IP: "192.168.1.105"    # Hardcoded IP address
          VM_PWD: ${{ secrets.VM_PWD }} # Accessing the corrected secret
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "$DEST_USER" "$DEST_IP" "$VM_PWD" "test.py"
