name: Run Python Script on Remote Ubuntu VM

on:
  workflow_dispatch:

jobs:
  execute-python:
    runs-on: self-hosted
    environment: ubuntu1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step to copy the Python script to the remote VM using scp
    - name: Copy Python Script to Remote VM
      run: |
        chmod +x copy_and_execute.sh
        ./copy_and_execute.sh \
          "karthik" "192.168.1.105" "${{ secrets.UBUNTU1 }}" "view_files.py"
