name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, X64, Linux]

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      - name: Copy and Execute Bash Script
        env:
          VMPWD: ${{ secrets.VM_PWD }}
        run: |
          chmod +x copy_file.sh
          ./copy_file.sh "karthik" "192.168.1.105" "$VMPWD" "test.py"
