name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, X64, Linux]

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      # Run the Bash script using the secret stored in GitHub
      - name: Copy and Execute Bash Script
        env:
          VMPWD: ${{ secrets.VM_PWD }}  # Reference the secret variable
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "$VMPWD" "test.py"
