name: Copy and Execute Script on Remote Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, X64, Linux]

    steps:
      - name: Checkout the Beta branch
        uses: actions/checkout@v3
        with:
          ref: Beta

      # Run the Bash script with hardcoded credentials
      - name: Copy and Execute Bash Script
        env:
          DEST_USER: "karthik"           # Hardcoded username
          DEST_IP: "192.168.1.105"       # Hardcoded IP address
          VMPWD: "Test@123"              # Hardcoded password
        run: |
          chmod +x copy_and_execute.sh
          ./copy_and_execute.sh "$DEST_USER" "$DEST_IP" "$VMPWD" "test.py"
